require('./frame/frame');
require('./player/player');
require('./playlistPanel/playlistPanel');
require('./playlistpanelitem/playlistPanelItem');
require('./playlistpaneloutput/playlistPanelOutput');
require('./progressbar/progressbar');
require('./songlist/songList');
require('./songlistitem/songListItem');
require('./toggle/toggle');
